---
name: Build and test

"on":
  push:
    branches: [main, rewrite]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-devcontainer:
    name: "Devcontainer: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [debug]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: swift test -c ${{ matrix.configuration }}

  build-native:
    name: "Native: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        configuration: [debug]
        include:
          - swift:
              version: '5.8'

          - os: windows-latest
            swift:
              version: '5.6'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift.version }}

      - name: Build and Test (${{ matrix.configuration }})
        run: swift test -c ${{ matrix.configuration }}
