---
name: Build and test

"on":
  push:
    branches: [main, rewrite]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-devcontainer:
    name: "Devcontainer: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [debug]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: swift test -c ${{ matrix.configuration }}

  build-native:
    name: "Native: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        configuration: [debug]
        include:
          # Default values to add
          - job-defaults:
              run:
                shell: bash -eo pipefail {0}

            setup-swift:
              action: swift-actions/setup-swift@v1
              with:
                swift-version: '5.8'

          # Overrides for the defaults
          - os: windows-latest

            job-defaults: []

            setup-swift:
              action: compnerd/gha-setup-swift@main
              with:
                github-repo: thebrowsercompany/swift-build
                release-asset-name: installer-amd64.exe
                release-tag-name: 20231010.3
                github-token: ${{ secrets.GITHUB_TOKEN }}

    defaults: ${{ matrix.job-defaults }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup swift
        uses: ${{ matrix.setup-swift.action }}
        with: ${{ matrix.setup-swift.with }}

      - name: Build and Test (${{ matrix.configuration }})
        run: swift test -c ${{ matrix.configuration }}
