---
name: Build and test

"on":
  push:
    branches: [main, rewrite]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-devcontainer:
    name: "Devcontainer: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      matrix:
        host: [
          {
            build-options: "-v --build-tests -Xswiftc -enable-testing",
            test-options: "-v",
          }
        ]
        os: [ubuntu-latest]
        configuration: [debug]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            swift test -c ${{ matrix.configuration }} \
              ${{ matrix.host.test-options }}

  build-native:
    name: "Native: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        host: [
          {
            build-options: "-v --build-tests -Xswiftc -enable-testing",
            test-options: "-v"
          }
        ]
        os: [macos-latest, ubuntu-latest, windows-latest]
        swift: [{version: "5.8"}]
        configuration: [debug]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift.version }}

      - name: Build and Test (${{ matrix.configuration }})
        run: |
          swift test -c ${{ matrix.configuration }} \
            ${{ matrix.host.test-options }}
